# This workflow will install Python dependencies, run security checks and lint

name: D3fend tools

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements.dev.txt
    - name: Lint with pylint
      run: |
        ./scripts/linter.sh
    - name: Package Auditing with safety
      run: |
        ./scripts/package-audit.sh
    - name: Code security check with bandit
      run: |
        ./scripts/security-check.sh
